[phases.setup]
nixPkgs = [
  "php",
  "phpPackages.composer",
  "php82Extensions.pdo_mysql",
  "php82Extensions.mbstring",
  "php82Extensions.curl",
  "php82Extensions.fileinfo",
  "php82Extensions.openssl",
  "php82Extensions.tokenizer",
  "php82Extensions.xml",
  "php82Extensions.dom",
  "php82Extensions.session",
  "nodejs_22",
  "curl"
]

[phases.install]
cmds = [
  "mkdir -p /app/bin",
  "curl -L https://github.com/dunglas/frankenphp/releases/latest/download/frankenphp-linux-x86_64 -o /app/bin/frankenphp",
  "chmod +x /app/bin/frankenphp"
]

[phases.build]
cmds = [
  "npm install",
  "npm run build",
  "composer install --no-dev --optimize-autoloader"
]
